import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello world! This is a <a href="https://nextjs.org">Next.js base app!</a>
        </h1>

        <p className={styles.description}>
          This is a simple demo showing Okta being used for authentication in NextJS. The goal is simple: allow users to log in with their Okta account, click to the private page, and then log back out.</p>
        
        <p className={styles.description}>Below are some links purely for filling up visual space. See the readme for details about NextJS and Okta used here.</p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>NextJS Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="/readme.md" className={styles.card}>
            <h2>Read Me &rarr;</h2>
            <p>Learn about this app.</p>
          </a>
        </div>
      </main>
    </div>
  )
}
